export const TEAM_REQUEST = 'TEAM_REQUEST'
export const TEAM_SUCCESS = 'TEAM_SUCCESS'
export const TEAM_ERROR = 'TEAM_ERROR'
export const TEAM_JOIN = 'TEAM_JOIN'
export const TEAM_CREATE = 'TEAM_CREATE'
export const TEAM_CLEAR = 'TEAM_CLEAR'
export const TEAM_SEARCH = 'TEAM_SEARCH'